// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playlist": {
    params: {};
  };
  "/schedule": {
    params: {};
  };
  "/layout": {
    params: {};
  };
  "/contents": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/player": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/playlist" | "/schedule" | "/layout" | "/contents" | "/login" | "/settings" | "/player";
  };
  "pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "components/layout/TabLayout.tsx": {
    id: "components/layout/TabLayout";
    page: "/playlist" | "/schedule" | "/layout" | "/contents";
  };
  "pages/Playlist.tsx": {
    id: "pages/Playlist";
    page: "/playlist";
  };
  "pages/Schedule.tsx": {
    id: "pages/Schedule";
    page: "/schedule";
  };
  "pages/Layout.tsx": {
    id: "pages/Layout";
    page: "/layout";
  };
  "pages/Contents.tsx": {
    id: "pages/Contents";
    page: "/contents";
  };
  "pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "pages/Settings.tsx": {
    id: "pages/Settings";
    page: "/settings";
  };
  "pages/Player.tsx": {
    id: "pages/Player";
    page: "/player";
  };
};